### PR TITLE
Refactor the development and release workflow

### PR DESCRIPTION
**Pull request by henri-hulski**
@faasen This PR provides the following changes:
- create universal wheels during release,
- move from buildout to pip/virtualenv,
- add development documentation,
- reorganize the documentation and change the html template to default,
- update CHANGES.txt,
- some clean-up.

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
recent tox added direct support for extras

**Comment by henri-hulski** [comment]
@RonnyPfannschmidt sounds interesting. Do you have a link to the documentation? I couldn't find it.

**Comment by RonnyPfannschmidt** [comment]
@henri-hulski http://tox.readthedocs.io/en/latest/config.html#confval-extras=MULTI-LINE-LIST

**Comment by RonnyPfannschmidt** [comment]
it came in with https://github.com/tox-dev/tox/pull/371

**Comment by henri-hulski** [comment]
@RonnyPfannschmidt  so what are the benefits of using extras vs. the way I use it? 

Are there any optimizations? 
Or it's just a cleaner syntax?

**Comment by RonnyPfannschmidt** [comment]
atm just cleaner syntax, in future the extras will be installed properly at env creation time instead of package install time

**Comment by henri-hulski** [comment]
But there is no regression atm, right?

**Comment by henri-hulski** [comment]
@RonnyPfannschmidt I changed it to use extras directly. Could you take a look if I did it the right way as there are no examples for this.

**Comment by henri-hulski** [comment]
BTW It looks really super clean now!

**Comment by henri-hulski** [comment]
@RonnyPfannschmidt If I want no extras in a testenv, would it be like:

``` ini
[testenv]
usedevelop = True
extras = test
commands = py.test {posargs}

[testenv:perf]
basepython = python3.5
extras =
commands = python {toxinidir}/tox_perf.py
```

Or should I use `extras = False` or something else?

**Comment by RonnyPfannschmidt** [comment]
Cant tell from my phone, please report against tox

**Pull request merged**
